// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SemantiCore_API.Infrastructure.Data;

#nullable disable

namespace SemantiCore_API.Migrations
{
    [DbContext(typeof(SemantiCoreDbContext))]
    [Migration("20260415100449_imamge url")]
    partial class imamgeurl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.CategoryIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndexCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IndexType")
                        .HasColumnType("int");

                    b.Property<string>("IndexValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndexCategoryId", "IndexName")
                        .IsUnique();

                    b.ToTable("CategoryIndexes");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkOrder")
                        .HasColumnType("int");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndexedDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndexedDocumentId", "ChunkOrder");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.DocumentEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentChunkId")
                        .HasColumnType("int");

                    b.Property<string>("Vector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentChunkId")
                        .IsUnique();

                    b.ToTable("DocumentEmbeddings");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.DocumentText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IndexedDocumentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndexedDocumentId");

                    b.ToTable("DocumentTexts");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.IndexCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("IndexCategories");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.IndexedDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryIndexId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryIndexId");

                    b.ToTable("IndexedDocuments");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.CategoryIndex", b =>
                {
                    b.HasOne("SemantiCore_API.Domain.Entities.IndexCategory", "IndexCategory")
                        .WithMany("CategoryIndexes")
                        .HasForeignKey("IndexCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexCategory");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("SemantiCore_API.Domain.Entities.IndexedDocument", "IndexedDocument")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("IndexedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexedDocument");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.DocumentEmbedding", b =>
                {
                    b.HasOne("SemantiCore_API.Domain.Entities.DocumentChunk", "DocumentChunk")
                        .WithMany("DocumentEmbeddings")
                        .HasForeignKey("DocumentChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentChunk");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.DocumentText", b =>
                {
                    b.HasOne("SemantiCore_API.Domain.Entities.IndexedDocument", null)
                        .WithMany()
                        .HasForeignKey("IndexedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.IndexedDocument", b =>
                {
                    b.HasOne("SemantiCore_API.Domain.Entities.CategoryIndex", "CategoryIndex")
                        .WithMany()
                        .HasForeignKey("CategoryIndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryIndex");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.DocumentChunk", b =>
                {
                    b.Navigation("DocumentEmbeddings");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.IndexCategory", b =>
                {
                    b.Navigation("CategoryIndexes");
                });

            modelBuilder.Entity("SemantiCore_API.Domain.Entities.IndexedDocument", b =>
                {
                    b.Navigation("DocumentChunks");
                });
#pragma warning restore 612, 618
        }
    }
}
